Dependencies:
 - 'on': ['@all']
   'require':
    'frameworks/extra-cmake-modules': '@same'

Options:
 test-before-installing: False
 require-passing-tests-on: ['Linux', 'FreeBSD']
 cmake-options: -DBUILD_EXAMPLES=OFF
